# Vote Count Prediction for new Images

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sklearn

## Loading Data

In [2]:
FEATS_FILE_PATH = os.path.join('..', 'features', 'incv1_feats.csv')
VOTES_FILE_PATH = os.path.join('..', 'results', 'votes_summary.csv')

#### Data (Features)

In [3]:
feats_df = pd.read_csv(FEATS_FILE_PATH, index_col=0)
feats_df.head(3)

0         1         2         3  \
1222__pool_table__0.9999995.jpg  0.882798  0.896023  0.123852  0.257982   
1328__coil__0.99999607.jpg       0.483815  0.134309  0.021849  0.367267   
134__zebra__0.9999949.jpg        0.291067  0.375913  0.217742  1.269691   

                                        4         5         6         7  \
1222__pool_table__0.9999995.jpg  0.036050  0.108023  0.633841  0.457301   
1328__coil__0.99999607.jpg       0.089250  0.007518  0.069921  0.219347   
134__zebra__0.9999949.jpg        0.384181  0.076470  0.662070  0.662391   

                                        8         9  ...      1014      1015  \
1222__pool_table__0.9999995.jpg  1.684949  0.285681  ...  0.422634  0.346122   
1328__coil__0.99999607.jpg       0.089260  0.046694  ...  0.049852  0.004140   
134__zebra__0.9999949.jpg        0.827774  0.115826  ...  0.018289  0.000000   

                                     1016      1017      1018      1019  \
1222__pool_table__0.9999995.jpg  0.111589  1.441579  0.198722  0.246648   
1328__coil__0.99999607.jpg       0.199223  0.718976  0.000000  0.000000   
134__zebra__0.9999949.jpg        0.000775  0.903884  0.589769  0.016957   

                                     1020      1021      1022      1023  
1222__pool_table__0.9999995.jpg  0.295942  0.560950  0.058328  0.117393  
1328__coil__0.99999607.jpg       0.000000  0.159411  0.012007  0.001601  
134__zebra__0.9999949.jpg        0.418493  0.005350  0.004198  0.185460  

[3 rows x 1024 columns]

#### Votes

In [4]:
votes_df = pd.read_csv(VOTES_FILE_PATH, index_col=0)
votes_df.head(3)

ig  lime  xrai  anchor  best
1222__pool_table__0.9999995.jpg  12    13     3       1  lime
1328__coil__0.99999607.jpg       17     4     3       2    ig
134__zebra__0.9999949.jpg        14     1     8       2    ig

Here's a sanity check for vote proportion in our the dataset. In the original XAI-CBR paper, vote proportion was like this:
- IG: 45%
- XRAI: 30%
- LIME: 18%
- ANCHOR: 7%

Also, IG was the most voted technique, at least by hard voting aggregation, with a majority of 62% images.


In [5]:
votes_df[['ig','lime','xrai','anchor']].sum() / 2867

ig        0.488315
lime      0.183467
xrai      0.271713
anchor    0.056505
dtype: float64

There's a slight imbalance of these proportions with respect to ones presented in the paper. It seems like some votes from XRAI and ANCHOR techniques drifted out to the IG technique. We'll check this out later, this should not be of great importance in the experiments of this notebook.

### Data Preprocessing

In [6]:
X = feats_df.values
X_names = feats_df.index.values
y = votes_df.values[:, :4]
best = votes_df.values[:, -1]

In [7]:
print(X.shape, X_names.shape, y.shape, best.shape)

(198, 1024) (198,) (198, 4) (198,)


#### Instance deletion
Stratified Subsampling cannot be performed onto the dataset because only one instance is best explained with ANCHOR. Due to the very small importance of that instance in the dataset, we will continue without that instance (i.e. we will find that instance and remove it from the dataset).

In [8]:
anchor_idxs = np.argwhere(best == 'anchor')[0]
anchor_idxs

array([155], dtype=int64)

In [9]:
X_names[anchor_idxs], best[anchor_idxs]

(array(['2411942__zebra__0.99999654.jpg'], dtype=object),
 array(['anchor'], dtype=object))

In [10]:
# Delete that instance from all data partitions (X, y, etc.)
X = np.delete(X, anchor_idxs, axis=0)
X_names = np.delete(X_names, anchor_idxs, axis=0)
y = np.delete(y, anchor_idxs, axis=0)
best = np.delete(best, anchor_idxs, axis=0)

In [11]:
print(X.shape, X_names.shape, y.shape, best.shape)

(197, 1024) (197,) (197, 4) (197,)


## Splitting and Fold Creation

In [12]:
from sklearn.model_selection import StratifiedShuffleSplit as SSS
from sklearn.model_selection import ShuffleSplit as SS

#### TODO: Should I perform statified subsampling or standard subsampling?

In [13]:
STRATIFIED = True

In [14]:
# Perform split
splitter = None
if STRATIFIED: splitter = SSS(n_splits=5, test_size=0.2, random_state=42)
else: splitter = SS(n_splits=5, test_size=0.2, random_state=42)
splits = splitter.split(X, best)
splits = list(splits)

In [15]:
splits[0]

(array([192, 147, 177,  11, 140,  51, 127, 118, 172, 191,  62, 124, 115,
         80, 190, 142,  92,  69,  25,  14,  42,   3, 185,  90,  10,  76,
        176, 114,  44,  98, 166, 121,  79, 170,   1, 183,  28,  31, 155,
         75, 156, 101, 171,  13, 110, 122,  38,  27, 136,  20,   6,  56,
         35,  59, 139,  33,  78,  82,  21, 167, 117,  12,  49,  15,   5,
        152, 132,  81,  61, 163, 175,  91,   7, 174, 135,  74, 193, 129,
         60,  96,  50, 161, 159, 145, 126,  19,  65, 188,  73,  89, 133,
        179,  40,  86, 112,  26, 168, 189, 149,  94, 194,  18, 138, 169,
        102,  97,  71, 130,  53,  99, 148, 154,   8,  34, 182, 105,  55,
         95, 153,  72, 144,  77,  52,  30,   9,  37,   4,  93, 128, 137,
        195, 160, 111,  45, 164, 151,  29,  48,  70,  43,  57, 157,  39,
        141,  85, 150,  67,   0,  47, 113,  32,  17, 131, 180,  66, 100,
        186], dtype=int64),
 array([ 54, 187, 103,  23, 104, 108, 181,  64, 109, 134,  16, 146,   2,
        116, 106, 119, 

## Clustering

In [78]:
clusterable_params = []

In [45]:
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score

In [55]:
def fit_dbscan(data, min_samples, eps_values, 
               min_no_clusters=2, max_no_clusters=np.inf,
               min_clust_instances=None, min_clust_instances_pct=0.85,
               max_clust_instances=np.inf, metric='euclidean'):
    # Condition precalculation
    if min_clust_instances_pct:
        min_clust_instances = round(data.shape[0] * min_clust_instances_pct)
    elif not min_clust_instances:
        min_clust_instances = 100
    # Code
    scores, clusters, instances = [], [], []
    for m in min_samples:
        row_scores, row_clusters, row_instances = [], [], []
        for e in eps_values:
            db = DBSCAN(min_samples=m, eps=e, metric=metric).fit(data)
            # Get only non anomalous instances
            non_a = db.labels_ != -1 # [False, ..., False] if all are outliers
            # Calculate conditions
            n_clusters = len(np.unique(db.labels_[non_a])) # 0 if all are outliers
            n_instances = len(db.labels_[non_a]) # 0 if all are outliers
            # Apply conditions (why does it output NaN and not None?)
            valid_n_clusters = n_clusters >= min_no_clusters and n_clusters <= max_no_clusters
            valid_n_cl_instances = n_instances >= min_clust_instances and n_instances <= max_clust_instances
            if (valid_n_clusters and valid_n_cl_instances):
                score = silhouette_score(data[non_a], db.labels_[non_a], metric=metric)
            else:
                score = None
            # Store results
            row_scores.append(score)
            row_clusters.append(n_clusters)
            row_instances.append(n_instances)
        # Store row results
        scores.append(row_scores)
        clusters.append(row_clusters)
        instances.append(row_instances)
    # Prepare and return values
    ms_axis = pd.Index(min_samples, name='Min_samples')
    eps_axis = pd.Index(eps_values, name='Epsilon')
    df_scores = pd.DataFrame(scores, index=ms_axis, columns=eps_axis)
    df_clusters = pd.DataFrame(clusters, index=ms_axis, columns=eps_axis)
    df_instances = pd.DataFrame(instances, index=ms_axis, columns=eps_axis)
    return df_scores, df_clusters, df_instances

In [70]:
def print_results(m, eps, scores_df, instances_df, clusters_df):
    score = round(scores_df.loc[m][eps], 4)
    instances = instances_df.loc[m][eps]
    clusters = clusters_df.loc[m][eps]
    print(f'DBSCAN using parameters m={m} and eps={eps} yields the next clustering results:')
    print()
    print(f'- Sil. score: {score}')
    print(f'- {instances} clustered instances into {clusters} clusters')
    print(f'- Avg. of {round(instances/clusters, 2)} instances per cluster')

In [57]:
X[splits[0][0]].shape[0] * 0.85 # about 135 clustered instances are needed

133.45

#### Split #0

In [62]:
dfs, dfc, dfi = fit_dbscan(X[splits[0][0]], range(2, 6), range(11, 18))
dfs

Epsilon        11    12        13        14        15        16        17
Min_samples                                                              
2            None  None  0.376409  0.309939  0.226041  0.169750  0.205307
3            None  None       NaN  0.306802  0.254193  0.207208  0.201926
4            None  None       NaN       NaN  0.262017       NaN       NaN
5            None  None       NaN       NaN  0.262017       NaN       NaN

In [60]:
print_results(2, 13, dfs, dfi, dfc)

DBSCAN using parameters m=2 and eps=13 yields the next clustering results:

- Sil. score: 0.3764090960818043
- 138 clustered instances into 16 clusters
- Avg. of 8.625 instances per cluster


In [79]:
clusterable_params.append([2, 13, 0])

#### Split #1

In [67]:
dfs, dfc, dfi = fit_dbscan(X[splits[1][0]], range(2, 7), range(11, 18))
dfs

Epsilon        11        12        13        14        15        16        17
Min_samples                                                                  
2            None  0.405127  0.388931  0.329026  0.233712  0.214392  0.279872
3            None       NaN       NaN  0.324064  0.235581  0.347616  0.336508
4            None       NaN       NaN       NaN  0.235581  0.347616  0.336508
5            None       NaN       NaN       NaN  0.242720  0.347616  0.336508
6            None       NaN       NaN       NaN  0.234807       NaN       NaN

In [65]:
print_results(2, 12, dfs, dfi, dfc)

DBSCAN using parameters m=2 and eps=12 yields the next clustering results:

- Sil. score: 0.405127456678934
- 135 clustered instances into 19 clusters
- Avg. of 7.105263157894737 instances per cluster


In [80]:
clusterable_params.append([2, 12, 1])

#### Split #2

In [71]:
dfs, dfc, dfi = fit_dbscan(X[splits[2][0]], range(2, 7), range(11, 18))
dfs

Epsilon        11        12       13        14        15       16        17
Min_samples                                                                
2            None  0.418787  0.41248  0.277547  0.230598  0.24841  0.244132
3            None       NaN  0.41020  0.269285  0.257609      NaN       NaN
4            None       NaN      NaN  0.269285  0.257609      NaN       NaN
5            None       NaN      NaN  0.275717  0.260715      NaN       NaN
6            None       NaN      NaN       NaN  0.254598      NaN       NaN

In [72]:
print_results(2, 12, dfs, dfi, dfc)

DBSCAN using parameters m=2 and eps=12 yields the next clustering results:

- Sil. score: 0.4188
- 136 clustered instances into 17 clusters
- Avg. of 8.0 instances per cluster


In [81]:
clusterable_params.append([2, 12, 2])

#### Split #3

In [73]:
dfs, dfc, dfi = fit_dbscan(X[splits[3][0]], range(2, 7), range(11, 18))
dfs

Epsilon        11        12        13        14        15        16        17
Min_samples                                                                  
2            None  0.403343  0.323821  0.278651  0.210186  0.184646  0.296871
3            None       NaN       NaN  0.273266  0.243847       NaN       NaN
4            None       NaN       NaN  0.270225  0.243847       NaN       NaN
5            None       NaN       NaN       NaN  0.242323       NaN       NaN
6            None       NaN       NaN       NaN  0.251365       NaN       NaN

In [74]:
print_results(2, 12, dfs, dfi, dfc)

DBSCAN using parameters m=2 and eps=12 yields the next clustering results:

- Sil. score: 0.4033
- 135 clustered instances into 19 clusters
- Avg. of 7.11 instances per cluster


In [82]:
clusterable_params.append([2, 12, 3])

#### Split #4

In [75]:
dfs, dfc, dfi = fit_dbscan(X[splits[4][0]], range(2, 7), range(11, 18))
dfs

Epsilon        11    12        13        14        15        16    17
Min_samples                                                          
2            None  None  0.372388  0.274406  0.216593  0.162722  None
3            None  None  0.398123  0.272670  0.262001       NaN  None
4            None  None       NaN  0.277303  0.262001       NaN  None
5            None  None       NaN       NaN  0.265082       NaN  None
6            None  None       NaN       NaN  0.274071       NaN  None

In [77]:
print_results(3, 13, dfs, dfi, dfc)

DBSCAN using parameters m=3 and eps=13 yields the next clustering results:

- Sil. score: 0.3981
- 133 clustered instances into 12 clusters
- Avg. of 11.08 instances per cluster


In [83]:
clusterable_params.append([3, 13, 4])

#### Clusterable parameters for each split

In [84]:
clusterable_params

[[2, 13, 0], [2, 12, 1], [2, 12, 2], [2, 12, 3], [3, 13, 4]]

## Clustering Results

In [49]:
def get_indiv_clustering_results(params):
    '''Returns a dictionary mapping the name of an image
    with the cluster it belongs'''
    # Prepare data
    instances = feats_df.values
    img_names = feats_df.index.values
    # Perform clustering
    dbscan = DBSCAN(min_samples=params[0], eps=params[1])
    dbscan = dbscan.fit(instances)
    # Generate {img_name : label} mapping
    name_label_map = {name: label for name, label in zip(img_names, dbscan.labels_)}
    return name_label_map

def get_global_clustering_results(params_set):
    '''Returns a dictionary mapping the index of every param set
    in 'params' arg. with the clustering results generated with that param. set'''
    results = {}
    for i, params in enumerate(params_set):
        results[i] = get_indiv_clustering_results(params)
    return results

In [53]:
cl_results = get_global_clustering_results([[2, 11],[4,12]])

In [63]:
np.unique(list(cl_results[0].values()))

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16], dtype=int64)

## Clustering Prototypes

In our experiment, we want to predict the vote count for a new image, based on the proximity it has to the avaliable clusters. These clusters are composed of many data points, so the proximity of a new data point to a cluster can be measured in different ways, like taking the distance between the new point and the nearest clustered point in the dataset.   
However, this approach can be biased when new poins get associated to the cluster taking in account the nearest point of a cluster instead of the overall position of a cluster. To avoid this, for each cluster we calculate a "prototype", a data point which is the centroid of all the data points in a cluster. This way, we can measure the distance to the general position of a cluster in a more confident way.

In [91]:
def gen_indiv_cl_prototypes(cl_result, ignore_noise=True):
    # Separate image data ("instances") according to the clusters they belong to
    instances_by_cluster = {}
    for img_name, cl_idx in cl_result.items():
        if ignore_noise and cl_idx == -1: continue # ignore noise cluster
        img_data = feats_df.loc[img_name].values
        if cl_idx not in instances_by_cluster.keys(): instances_by_cluster[cl_idx] = [img_data]
        else: instances_by_cluster[cl_idx].append(img_data)
    # For each cluster, calculate their prototype
    prototypes_per_cluster = {}
    for cl_idx, instances in instances_by_cluster.items():
        prototypes_per_cluster[cl_idx] = np.average(instances, axis=0)
    return prototypes_per_cluster
    
def get_global_cl_prototypes(cl_results, ignore_noise=True):
    global_prototypes = {}
    for i, cl_result in cl_results.items():
        global_prototypes[i] = gen_indiv_cl_prototypes(cl_result, ignore_noise=ignore_noise)
    return global_prototypes

In [92]:
cls_prototypes = get_global_cl_prototypes(cl_results)

In [94]:
cls_prototypes[0]

{0: array([0.66188401, 0.93429005, 0.11197158, ..., 0.88486853, 0.21662746,
        0.12339265]),
 1: array([0.50070014, 0.99811866, 0.28720732, ..., 0.01932118, 0.02779637,
        0.02556516]),
 2: array([0.19200545, 1.58048682, 0.25523968, ..., 0.81177693, 0.4258423 ,
        0.43064069]),
 3: array([0.14667615, 0.67061676, 1.162989  , ..., 0.28520836, 2.17391784,
        0.1788621 ]),
 4: array([0.6160234 , 0.20189823, 0.1508589 , ..., 0.21690794, 0.17138973,
        0.51319627]),
 5: array([0.53928549, 2.23871909, 0.32241292, ..., 0.43548633, 0.04817468,
        0.50577198]),
 6: array([0.17033383, 0.11921771, 0.6543898 , ..., 0.0605856 , 0.30521156,
        0.06356359]),
 7: array([0.19044175, 0.09295808, 0.18133281, ..., 0.35558084, 0.24817289,
        0.74048979]),
 8: array([0.85294944, 0.64817178, 0.74822995, ..., 0.1904317 , 0.54083599,
        0.05673566]),
 9: array([0.56155054, 0.10792938, 1.53658396, ..., 0.19078673, 0.98497629,
        0.21381244]),
 10: array([0.324671

## Evaluation